--------------------------------------------------------
--  DDL for Table AIRLINES
--------------------------------------------------------

  CREATE TABLE "AIRLINES" 
   (	"AIRLINES_ICAO_CODE" CHAR(5 BYTE), 
	"AIRLINE_NAME" VARCHAR2(40 BYTE), 
	"AIRLINE_CALL_SIGN" VARCHAR2(30 BYTE), 
	"AIRLINE_COUNTRY" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
