REM INSERTING into AIRPORTS
SET DEFINE OFF;
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KRK','John Paul II International Airport','Balice, Poland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KEL','Kiel Holtenau Airport','Kiel, Schleswig-Holstein, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DND','Dundee Airport','Dundee, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GSY','RAF Binbrook','Grimsby, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ODS','Odessa International Airport','Odessa, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GHF','Giebelstadt Airport','Giebelstadt, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CEJ','Chernihiv Shestovitsa Airport','Chernihiv, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VBY','Visby Airport','Visby, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BBS','Blackbushe Airport','Yateley, Hampshire, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GOT','Gothenburg-Landvetter Airport','Gothenburg, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KID','Kristianstad Airport','Kristianstad, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('EXT','Exeter International Airport','Exeter, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('IDB','Idre Airport','Idre, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('REU','Reus Airport','Reus (near Tarragona), Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GME','Gomel Airport','Gomel, Belarus');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OVD','Asturias Airport','Oviedo, Asturias, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MAN','Manchester Airport','Manchester, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ESH','Shoreham Airport','Lancing, West Sussex, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BBU','Bucharest "Aurel Vlaicu" Airport','Bucharest, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('YEO','RNAS Yeovilton','Yeovilton, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KHC','Kerch Airport','Kerch, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ERD','Berdyansk Airport','Berdyansk, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TGA','Tengah Air Base','Tengah, Singapore');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BRE','Bremen Airport','Bremen, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HMJ','Khmelnytsky Airport','Khmelnytsky, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SDR','Santander - Parayas Airport','Santander, Cantabria, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HAW','Haverfordwest Aerodrome','Haverfordwest, Wales, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QFO','Duxford Airport','Duxford, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('IBZ','Ibiza Airport','Ibiza, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LUG','Lugano Airport','Lugano, Agno, Switzerland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CAL','Campbeltown Airport','Campbeltown, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KBP','Boryspil International Airport','Kiev, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('IOM','Isle of Man Airport','Ronaldsway, Isle of Man, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FDH','Friedrichshafen Airport','Friedrichshafen, Bodensee, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FZO','Bristol Filton Airport','Filton, Bristol, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('WXF','MDPGA Wethersfield','Braintree, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('RIX','Riga International Airport','Riga, Latvia');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BIO','Bilbao Airport','Bilbao, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OBF','Oberpfaffenhofen Airport','Oberpfaffenhofen, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DOK','Donetsk International Airport','Donetsk, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HSK','Huesca-Pirineos Airport','Huesca, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('PMI','Palma de Mallorca Airport','Palma de Mallorca, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BRS','Bristol Airport','Bristol, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GLO','Gloucester Airport','Gloucester / Cheltenham, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MHG','Mannheim City Airport','Mannheim, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HHN','Frankfurt-Hahn Airport','Rhineland-Palatinate, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SIP','Simferopol International Airport','Simferopol, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HOQ','Hof Airport','Hof,  Bavaria, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MPW','Mariupol Airport','Mariupol, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CLJ','Cluj-Napoca International Airport','Cluj-Napoca, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FUE','El Matorral Airport','Puerto del Rosario, Fuerteventura, Canary Islands, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BQT','Brest Airport','Brest, Belarus');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SCS','Scatsta Airport','Shetland Islands, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('AGE','Wangerooge Airport','Wangerooge, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DVA','Deva Airport','Deva, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ACH','St. Gallen Altenrhein Airport','Altenrhein, Switzerland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QPK','Strausberg Airport','Strausberg, Brandenburg, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('JHE','Hamnen Heliport','Helsingborg, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ABZ','Aberdeen Airport','Aberdeen, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('JLD','Landskrona Heliport','Landskrona, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LTN','London Luton Airport','Luton (near London), England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TAT','Poprad-Tatry Airport','Poprad, Slovakia');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BYU','Bindlacher Berg Airport','Bayreuth, Bavaria, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CWL','Cardiff Airport','Cardiff, Wales, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BFS','Belfast International Airport','Belfast, Northern Ireland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LDY','City of Derry Airport','Derry, Northern Ireland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QMZ','Mainz-Finthen Airport','Mainz, Rhineland-Palatinate, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OBL','Zoersel-Oostmalle Airfield','Zoersel / Oostmalle, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CAX','Carlisle Lake District Airport','Carlisle, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('RLG','Rostock Laage Airport','Rostock, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CBU','Cottbus-Drewitz Airport','Cottbus, Brandenburg, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MHP','Minsk-1 Airport','Minsk, Belarus');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ACI','Alderney Airport','Alderney, Channel Islands, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ALC','El Altet Airport','Alicante, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BEX','RAF Benson','Benson, Oxfordshire, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NOD','Norden-Norddeich Airport','Norden, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SUJ','Satu Mare International Airport','Satu Mare, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SVQ','San Pablo Airport','Seville, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BWF','Barrow/Walney Island Airfield','Barrow-in-Furness, Cumbria, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SCQ','Santiago de Compostela Airport','Santiago de Compostela, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FAB','Farnborough Airport','Farnborough, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HUV','Hudiksvall Airport','Hudiksvall, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('STR','Stuttgart Airport','Stuttgart, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('PSL','Perth Airport (Scotland)','Perth, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ZAZ','Zaragoza Airport','Zaragoza, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BMA','Stockholm-Bromma Airport','Stockholm, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LBA','Leeds Bradford International Airport','Leeds / Bradford, West Yorkshire, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GWW','RAF Gatow','Berlin, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NLV','Mykolaiv Airport','Mykolaiv, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LEU','La Seu d''Urgell Airport','La Seu d''Urgell, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BFE','Bielefeld Airport','Bielefeld, North Rhine-Westphalia, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HAJ','Hannover-Langenhagen Airport','Hanover, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ZTR','Zhytomyr Airport','Zhytomyr, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KTW','Katowice Airport','Katowice / Pyrzowice, Poland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BHD','George Best Belfast City Airport','Belfast, Northern Ireland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('RCS','Rochester Airport','Rochester, Kent, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KOI','Kirkwall Airport','Kirkwall, Orkney Islands, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ZCN','Celle Air Base','Celle, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ORM','Sywell Aerodrome','Northampton / Peterborough, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FRA','Frankfurt Airport','Frankfurt, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KSF','Kassel Calden Airport','Kassel, Hesse, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ANR','Antwerp International Airport','Antwerp, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HAD','Halmstad Airport','Halmstad, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BBH','Stralsund Barth Airport','Barth, Mecklenburg-Vorpommern, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HUY','Humberside Airport','North Lincolnshire, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DGP','Daugavpils International Airport','Daugavpils, Latvia');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LYE','RAF Lyneham','Wiltshire, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ARW','Arad International Airport','Arad, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FNB','Neubrandenburg Airport','Neubrandenburg, Mecklenburg-Vorpommern, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('EME','Emden Airport','Emden, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('RNB','Ronneby Airport','Ronneby, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TFS','Tenerife South Airport','Tenerife, Canary Islands, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FSS','RAF Kinloss','Forres, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BOH','Bournemouth Airport','Bournemouth, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('PSY','Port Stanley Airport','Stanley, Falkland Islands, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GVA','Cointrin International Airport','Geneva, Switzerland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LEJ','Leipzig/Halle Airport','Leipzig, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('POS','Piarco International Airport','Piarco (near Port of Spain), Trinidad and Tobago');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HLF','Hultsfred-Vimmerby Air Base','Hultsfred / Vimmerby, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HTF','Hatfield Aerodrome','Hatfield, Hertfordshire, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KNO','Westkapelle Airport','Knokke-Heist, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('PAD','Paderborn/Lippstadt Airport','Paderborn, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ODH','RAF Odiham','Odiham, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QLA','Lasham Airfield','Lasham, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KNF','RAF Marham','Marham, Norfolk, East Anglia, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BXO','Buochs Airport','Buochs, Switzerland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BHX','Birmingham Airport','Birmingham, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OST','Ostend-Bruges International Airport','Flanders, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BEQ','RAF Honington','Bury St. Edmunds, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GRO','Girona-Costa Brava Airport','Girona, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('IFO','Ivano-Frankivsk Airport','Ivano-Frankivsk, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BLK','Blackpool International Airport','Blackpool, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OXF','London Oxford Airport','Oxford, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MTS','Matsapha Airport','Manzini, Swaziland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BBJ','Bitburg Airport','Bitburg, Rhineland-Palatinate, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TXL','Berlin Tegel Airport','Tegel / Berlin, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BRV','Bremerhaven Airport','Bremerhaven, Bremen, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DTM','Dortmund Airport','Dortmund, North Rhine-Westphalia, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HRK','Kharkiv International Airport','Kharkiv, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('IEV','Kiev International Airport','Kiev, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KSK','Karlskoga Airport','Karlskoga, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QUG','Goodwood Airfield','Chichester, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BRU','Brussels Airport','Brussels, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ACE','Lanzarote Airport','Arrecife, Canary Islands, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SBZ','Sibiu International Airport','Sibiu, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LUZ','Lublin Airport','Lublin, Poland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LPA','Gran Canaria International Airport','Las Palmas, Canary Islands, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('IGS','Ingolstadt Manching Airport','Ingolstadt, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CWC','Chernovtsy Airport','Chernivtsi, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BBP','Bembridge Airport','Bembridge, Isle of Wight, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LGO','Langeoog Airport','Langeoog, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QPG','Paya Lebar Air Base','Paya Lebar, Singapore');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MVQ','Mogilev Airport','Mogilev, Belarus');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('WAW','Frederic Chopin International Airport','Warsaw, Poland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('RWN','Rovno Airport','Rivne, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TRE','Tiree Airport','Tiree, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SEX','Sembach Air Base','Sembach, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SWS','Swansea Airport','Swansea, Wales, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('EKT','Eskilstuna Airport','Eskilstuna, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MVA','Reykjahlid Airport','Myvatn, Iceland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LKZ','RAF Lakenheath','Lakenheath, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GCI','Guernsey Airport','Guernsey, Channel Islands, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LPL','Liverpool John Lennon Airport','Liverpool, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DSA','Robin Hood Airport Doncaster Sheffield','Doncaster, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('JUI','Juist Airport','Juist, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('XSP','Seletar Airport','Seletar, Singapore');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SOY','Stronsay Airport','Stronsay, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CGN','Cologne Bonn Airport','Cologne, North Rhine-Westphalia, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LSI','Sumburgh Airport','Shetland, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('WBG','Fliegerhorst Schleswig','Schleswig, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CQM','Ciudad Real Central Airport','Ciudad Real, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GNE','St. Denijs-Westrem Airport','Ghent, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SIR','Sion Airport','Sion, Switzerland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NDZ','Cuxhaven Airport','Nordholz-Spieka, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VSG','Luhansk Airport','Luhansk (Lugansk), Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VEY','Vestmannaeyjar Airport','Vestmannaeyjar, Iceland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DGX','MOD St Athan','St Athan, Wales, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NQY','Newquay Cornwall International Airport','Newquay, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QSA','Sabadell Airport','Catalonia, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SGE','Siegerland Airport','Burbach, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HRT','Linton-On-Ouse Airport','Harrogate, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HLY','Anglesey Airport','Anglesey, Wales, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KSD','Karlstad Airport','Karlstad, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('WMI','Modlin Airport','Warsaw, Poland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NWI','Norwich International Airport','Norwich, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LHR','London Heathrow Airport','London, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MUC','Munich Airport','Munich, Bavaria, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CRL','Brussels South Charleroi Airport','Charleroi, Wallonia, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SEN','London Southend Airport','Southend, Essex (near London) United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OTP','Henri Coanda International Airport','Otopeni (near Bucharest), Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MSE','Kent International Airport','Manston, Kent, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('DRS','Dresden Airport','Dresden, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('WIC','Wick Airport','Wick, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SIN','Singapore Changi Airport','Changi, Singapore');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MSQ','Minsk International Airport','Minsk, Belarus');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NDY','Sanday Airport','Sanday, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LGW','London Gatwick Airport','London, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BCN','Barcelona El Prat Airport','El Prat de Llobregat (near Barcelona), Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TSO','Tresco Heliport','Tresco, Isles of Scilly, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GML','Gostomel Airport','Kiev, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('EVG','Sveg Airport','Sveg, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VHM','Vilhelmina Airport','Vilhelmina, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BRN','Bern Airport','Bern, Switzerland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NRD','Norderney Airport','Norderney, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ARN','Stockholm Arlanda Airport','Stockholm, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LWK','Tingwall Airport','Lerwick, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QHA','Kiewit Airport','Hasselt, Belgium');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HMV','Hemavan Airport','Hemavan, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SCV','Suceava Airport','Suceava, Romania');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('PNA','Pamplona Airport','Pamplona, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('PLH','Plymouth City Airport','Plymouth, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ERF','Erfurt Airport','Erfurt, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('INV','Inverness Airport','Inverness, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NHT','RAF Northolt','Ruislip, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('OKH','RAF Cottesmor','Oakham, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SPM','Spangdahlem Air Base','Spangdahlem, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('XFW','Hamburg Finkenwerder Airport','Hamburg, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BZG','Bydgoszcz Ignacy Jan Paderewski Airport','Bydgoszcz, Poland');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('NCL','Newcastle Airport','Newcastle upon Tyne, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('JER','Jersey Airport','Jersey, Channel Islands, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SOU','Southampton Airport','Eastleigh (near Southampton), England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BUD','Budapest Ferenc Liszt International Airport','Budapest, Hungary');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ENK','Enniskillen/St Angelo Airport','Enniskillen, Co Fermanagh, Northern Ireland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KRQ','Kramatorsk Airport','Kramatorsk, Donetsk Oblast, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('QCY','RAF Coningsby','Coningsby, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BQH','London Biggin Hill Airport','Biggin Hill / London, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ZPQ','Rheine Air Base','Rhine, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('XLW','Lemwerder Airport','Lemwerder, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BMR','Baltrum Airport','Baltrum, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('RGS','Burgos Airport','Burgos, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GLA','Glasgow International Airport','Glasgow, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('BRR','Barra Airport','Barra, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HFS','Hagfors Airport','Hagfors, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('WVN','JadeWeser Airport','Wilhelmshaven, Lower Saxony, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KGO','Kirovograd Airport','Kirovohrad, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VIT','Vitoria Foronda International Airport','Vitoria-Gasteiz, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MCQ','Miskolc Airport','Miskolc, Hungary');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('LYM','Lympne Airport','Lympne, Kent, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MJV','Murcia-San Javier Airport','Murcia, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CKC','Cherkasy Airport','Cherkasy, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GWT','Sylt Airport','Westerland, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('EMA','East Midlands Airport','Castle Donington, Leicestershire, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MNI','John A. Osborne Airport','Montserrat, British Overseas Territories, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('FFD','RAF Fairford','Fairford, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ILD','Lleida-Alguaire Airport','Lleida, Spain ');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('MAH','Mahon Airport','Menorca, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CSO','Magdeburg-Cochstedt Airport','Magdeburg, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('TFN','Tenerife North Airport','Tenerife, Canary Islands, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VGO','Vigo-Peinador Airport','Galicia, Spain');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('VIN','Gavryshivka International','Vinnytsia, Ukraine');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('CEG','Hawarden Airport','Chester, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('KLR','Kalmar Airport','Kalmar, Sweden');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('GKE','NATO Air Base Geilenkirchen','Geilenkirchen,  North Rhine-Westphalia, Germany');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('ILY','Port Ellen Airport','Islay, Scotland, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('HYC','RAF High Wycombe','High Wycombe, Buckinghamshire, England, United Kingdom');
Insert into AIRPORTS (AIRPORT_CODE,AIRPORT_NAME,AIRPORT_LOCATION) values ('SPC','La Palma Airport','La Palma, Canary Islands, Spain');
