REM INSERTING into CANCELED_TICKETS
SET DEFINE OFF;
Insert into CANCELED_TICKETS (TICKET_CODE,PASS_ID,FLIGHT_CODE) values ('AYZ208/538','201','AYZ208');
Insert into CANCELED_TICKETS (TICKET_CODE,PASS_ID,FLIGHT_CODE) values ('AEH134/3','188','AEH134');
