--create separate tablespace for database
CREATE TABLESPACE tbs_dwh 

/******************** change path for data file to your directory*/

DATAFILE 'D:\tbs_dwh.dat' size 5M autoextend ON next 5M MAXSIZE unlimited;

--KRAUTSOVA_LISHTVAN_SHCHARBUK schema 

CREATE USER KRAUTSOVA_LISHTVAN_SHCHARBUK IDENTIFIED BY root
    DEFAULT TABLESPACE tbs_dwh
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON tbs_dwh; 

GRANT CONNECT TO KRAUTSOVA_LISHTVAN_SHCHARBUK;
GRANT CREATE SESSION TO KRAUTSOVA_LISHTVAN_SHCHARBUK;
GRANT CREATE TABLE TO KRAUTSOVA_LISHTVAN_SHCHARBUK;
GRANT CREATE SEQUENCE TO KRAUTSOVA_LISHTVAN_SHCHARBUK;
GRANT CREATE PUBLIC SYNONYM TO KRAUTSOVA_LISHTVAN_SHCHARBUK;
GRANT CREATE PROCEDURE TO KRAUTSOVA_LISHTVAN_SHCHARBUK;

