-- CREATE SCHEMA
@'D:/SiTAiRIS_CP/DB_scripts/CREATE KRAUTSOVA_LISHTVAN_SHCHARBUK SCHEMA.SQL';
--CREATE DDL FOR TABLES
@'D:/SiTAiRIS_CP/DB_scripts/ARILINES.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/AIRPORTS.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/CANCELED_TICKETS.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/FLIGHTS.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PASSENGERS.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PILOTS.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PRICES.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/TICKETS.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/USERS.SQL';
--CREATE CONSTRAINTS
@'D:/SiTAiRIS_CP/DB_scripts/AIRLINES_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/AIRPORTS_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/CANCELED_TICKETS_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/CANCELED_TICKETS_REFCONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/FLIGHTS_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/FLIGHTS_REFCONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PASSENGERS_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PASSENGERS_REFCONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PILOTS_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PRICES_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PRICES_REFCONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/TICKETS_CONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/TICKET_REFCONSTRAINT.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/USERS_CONSTRAINT.SQL';
--CREATE INDEXES
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007777.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007778.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007779.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007780.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007781.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007782.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007799.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007985.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/SYS_C007988.SQL';
--INSERT DATA
@'D:/SiTAiRIS_CP/DB_scripts/ARILINES_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/AIRPORTS_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/CANCELED_TICKETS_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/FLIGHTS_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PASSENGERS_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PILOTS_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/PRICES_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/TICKETS_DATA_TABLE.SQL';
@'D:/SiTAiRIS_CP/DB_scripts/USERS_DATA_TABLE.SQL';

