--------------------------------------------------------
--  DDL for Table FLIGHTS
--------------------------------------------------------

  CREATE TABLE "FLIGHTS" 
   (	"FLIGHT_CODE" VARCHAR2(30 BYTE), 
	"FLIGHT_DISTANCE" NUMBER, 
	"AIRLINE_CODE" CHAR(5 BYTE), 
	"AIRPORT_FROM" VARCHAR2(10 BYTE), 
	"AIRPORT_TO" VARCHAR2(10 BYTE), 
	"PILOT_ID" NUMBER, 
	"COPILOT_ID" NUMBER, 
	"F_DATE" TIMESTAMP (6), 
	"NUM_OF_ECONOMY" NUMBER, 
	"NUM_OF_BUSINESS" NUMBER, 
	"T_DATE" TIMESTAMP (6), 
	"NUM_OF_FIRST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
