--------------------------------------------------------
--  Ref Constraints for Table FLIGHTS
--------------------------------------------------------

  ALTER TABLE "FLIGHTS" ADD FOREIGN KEY ("AIRPORT_FROM")
	  REFERENCES "AIRPORTS" ("AIRPORT_CODE") ENABLE;
  ALTER TABLE "FLIGHTS" ADD FOREIGN KEY ("AIRLINE_CODE")
	  REFERENCES "AIRLINES" ("AIRLINES_ICAO_CODE") ENABLE;
  ALTER TABLE "FLIGHTS" ADD FOREIGN KEY ("AIRPORT_TO")
	  REFERENCES "AIRPORTS" ("AIRPORT_CODE") ENABLE;
  ALTER TABLE "FLIGHTS" ADD FOREIGN KEY ("PILOT_ID")
	  REFERENCES "PILOTS" ("PILOT_ID") ENABLE;
  ALTER TABLE "FLIGHTS" ADD FOREIGN KEY ("COPILOT_ID")
	  REFERENCES "PILOTS" ("PILOT_ID") ENABLE;
