REM INSERTING into PASSENGERS
SET DEFINE OFF;
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('186','Lubov','Bogdanovich','Russia','KL5698741','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('201','Lubov','Bogdanova','USA','AZ123489','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('185','rtey','q','q','w','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('245','Lubov','Bogdanova','Belarus','12345tr','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('1','Valli','Gee','United Kingdom','BC1234567',null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('2','Alexander','Olson','Russia','DF4563761',null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('3','Alexander','Errazuriz','Slovakia','CD6589412',null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('4','Luis','Philtanker','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('5','Sigal','Marlow','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('6','Alexander','Mikkilineni','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('7','John','Mikkilineni','Romania',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('8','Shelli','Cambrault','Sweden',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('9','Sigal','Ladwig','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('10','Bruce','Fripp','Hungary',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('11','Diana','Partners','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('12','Ismael','Partners','Russia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('13','Luis','Mikkilineni','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('14','Diana','Bissot','Spain',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('15','David','Vargas','Brazil',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('16','Valli','Philtanker','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('17','Luis','Atkinson','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('19','Neena','Matos','Romania',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('20','David','Fripp','United States',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('21','David','Marlow','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('22','Den','Rajs','Brazil',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('23','Luis','Marlow','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('24','Neena','Mallin','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('25','Neena','Mikkilineni','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('26','Jose Manuel','Gee','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('27','Sigal','Fripp','Latvia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('28','Daniel','Matos','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('29','Jose Manuel','Seo','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('30','Nancy','Mourgos','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('31','Valli','Mikkilineni','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('32','Diana','Marlow','Hong Kong',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('33','Luis','Vollman','Hungary',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('34','Neena','Patel','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('35','Sigal','Mourgos','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('36','Daniel','Rajs','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('37','Guy','Seo','Romania',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('38','Nancy','Markle','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('39','Alexander','Marlow','United States',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('40','Alexander','Mallin','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('41','Bruce','Matos','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('42','Luis','Cambrault','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('43','Daniel','Olson','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('44','Diana','Markle','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('45','Steven','Kaufling','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('46','Alexander','Partners','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('47','Bruce','Rogers','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('48','John','Philtanker','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('49','Shelli','Russell','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('50','Alexander','Ladwig','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('51','Shelli','Kaufling','Russia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('52','Valli','Nayer','Russia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('53','Guy','Davies','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('54','Ismael','Philtanker','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('55','Shelli','Mourgos','Hong Kong',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('56','Steven','Bissot','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('57','Jose Manuel','Mikkilineni','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('58','Steven','Weiss','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('59','Valli','Weiss','Brazil',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('60','Lex','Matos','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('61','Ismael','Fripp','Belgium',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('62','Alexander','Philtanker','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('63','Alexander','Marlow','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('64','Sigal','Atkinson','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('65','Den','Fripp','Swaziland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('66','Den','Patel','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('67','Lex','Bissot','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('68','Shelli','Landry','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('69','Alexander','Nayer','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('70','Alexander','Stiles','Thailand',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('71','Den','Kaufling','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('72','David','Philtanker','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('73','Lex','Stiles','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('74','Nancy','Fripp','Brazil',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('75','Guy','Mourgos','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('76','Alexander','Rogers','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('77','Diana','Cambrault','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('78','John','Mourgos','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('79','Ismael','Marlow','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('80','Ismael','Vargas','Hong Kong',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('81','Bruce','Nayer','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('82','Steven','Vollman','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('83','Bruce','Errazuriz','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('84','Sigal','Nayer','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('85','Valli','Marlow','Swaziland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('86','Lex','Rajs','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('87','Ismael','Nayer','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('88','Jose Manuel','Mallin','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('89','Sigal','Mikkilineni','Brazil',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('90','Sigal','Seo','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('91','Alexander','Vargas','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('92','Jose Manuel','Weiss','Swaziland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('93','Alexander','Fripp','Russia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('94','Bruce','Partners','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('95','John','Vargas','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('96','David','Seo','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('97','Jose Manuel','Fripp','Spain',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('98','Shelli','Olson','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('99','Daniel','Mikkilineni','Sweden',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('100','Ismael','Davies','Germany',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('101','Neena','Rogers','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('102','Lex','Gee','Latvia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('103','Den','Mourgos','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('104','Lex','Rogers','Sweden',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('105','Diana','Mourgos','Belgium',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('106','Steven','Mallin','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('107','Alexander','Weiss','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('108','Jose Manuel','Atkinson','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('109','Daniel','Mallin','United States',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('110','David','Landry','Sweden',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('111','Ismael','Weiss','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('112','Nancy','Davies','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('113','John','Patel','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('114','David','Vollman','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('115','John','Markle','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('116','Neena','Philtanker','Hong Kong',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('117','Valli','Davies','Belgium',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('118','Lex','Fripp','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('119','John','Landry','Swaziland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('120','Neena','Fripp','Thailand',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('121','Valli','Fripp','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('122','Bruce','Olson','Thailand',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('123','Alexander','Stiles','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('124','Bruce','Bissot','Romania',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('125','Nancy','Kaufling','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('126','Nancy','Russell','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('127','Valli','Ladwig','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('128','Daniel','Vollman','Hong Kong',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('129','David','Errazuriz','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('130','Diana','Vargas','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('131','Steven','Markle','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('132','Guy','Fripp','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('133','Alexander','Cambrault','Sweden',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('134','Luis','Stiles','Latvia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('135','Neena','Atkinson','Brazil',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('136','Shelli','Mikkilineni','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('137','Steven','Patel','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('138','Ismael','Bissot','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('139','John','Ladwig','Sweden',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('140','Daniel','Fripp','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('141','Alexander','Patel','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('142','John','Matos','Russia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('143','Valli','Partners','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('144','Guy','Rajs','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('145','Daniel','Markle','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('146','Diana','Fripp','Romania',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('147','Shelli','Fripp','Slovakia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('148','Alexander','Atkinson','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('149','Nancy','Partners','Romania',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('150','David','Gee','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('151','Steven','Fripp','Hong Kong',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('152','Daniel','Bissot','Iceland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('153','Guy','Rogers','Singapore',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('154','John','Fripp','Ukraine',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('155','Lex','Ladwig','Hungary',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('156','Diana','Gee','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('157','Ismael','Ladwig','United Kingdom',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('158','Sigal','Markle','Germany',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('159','Lex','Davies','Russia',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('160','Luis','Fripp','India',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('161','Luis','Vargas','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('162','Shelli','Stiles','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('163','Jose Manuel','Rajs','Italy',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('164','Guy','Olson','Switzerland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('165','Alexander','Vollman','Swaziland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('166','Neena','Nayer','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('167','Guy','Vollman','Japan',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('168','Bruce','Cambrault','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('169','Guy','Landry','Belarus',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('170','Sigal','Bissot','Singapore',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('171','Nancy','Patel','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('172','Steven','Russell','Poland',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('173','Steven','Partners','Spain',null,null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('222',null,null,'Belarus',null,'qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('202','zxc','vfh','Belarus','12hj5g','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('187','Nastya','Scherbuk','Belarus','z1z1z1','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('188','Lubov','Bogdanova','USA','MN1425367','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('221','Anastasia','Scherbuk','Belarus','QW123456z','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('242','a','s','Belarus','q','qwerty');
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('246','Alex','Qwerty','Russia','nmhjyi43',null);
Insert into PASSENGERS (PASS_ID,FIRST_NAME,LAST_NAME,COUNTRY,PASSPORT_NUM,USERNAME) values ('183','Anastasia','Scherbuk','Belarus','ZX9863452',null);
